title: George Ugwu # your name (or website title) here
logo: "/images/georgeImage.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Enthusiastic Engineer 
  <br><br>
  Data, AI, Python Engineer 
  <br><br>
  <a href="https://www.linkedin.com/in/george-c-ugwu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-GBKJJBTYWP # your Google Analytics tracking ID here
